### ISSUE TITLE
Compiling on Mint 18 / Ubuntu 16.04

### ISSUE THREAD

**Issue by rghvdberg** [sjaehn/BSlizr#3]
Hi, thanks for this awesome plugin.

In order to compile BSlicer on Mint 18 (== Ubuntu 16.04) I had to:

1. comment out https://github.com/sjaehn/BSlicer/blob/master/src/BSlicer_GUI.cpp#L32
"looparray.hpp" isn't in the source tree, as far as I can tell
2. add  `-std=c++11` to  https://github.com/sjaehn/BSlicer/blob/master/makefile#L13 and https://github.com/sjaehn/BSlicer/blob/master/makefile#L17
`$(CC) $< -o $(BUNDLE)/$@ -std=c++11 -shared -fPIC -DPIC `pkg-config --cflags --libs lv2``
`$(CC) $< $(TK) -o $(BUNDLE)/$@ -std=c++11 -shared -DPUGL_HAVE_CAIRO -fPIC -DPIC `pkg-config --cflags --libs lv2 x11 cairo``

**Comment by sjaehn** [comment]
Thanks for your feedback. You are right.
1) "looparray.hpp" is a zombie. => removed.
2) Added.
