### ISSUE TITLE
make install target doesn't honor DESTDIR

### ISSUE THREAD

**Issue by dvzrv** [sjaehn/BSlizr#5]
Hi! I'm about to package bslizr for Arch Linux.
I noticed, that the Makefile doesn't honor [DESTDIR](https://www.gnu.org/prep/standards/html_node/DESTDIR.html) at all, which is not so nice, as it now has to be hardcoded within the custom `INSTALL_DIR`.

It would be great if it could be changed to the more generic and widely adopted `DESTDIR` and `PREFIX` (see https://www.gnu.org/prep/standards/html_node/Directory-Variables.html#Directory-Variables as reference).

**Comment by sjaehn** [comment]
Yes, thanks. This is better. Fixed in c1b120094f9d3ae55244cec4b2b72013da04c06b.
