### ISSUE TITLE
lacks full RELRO

### ISSUE THREAD

**Issue by dvzrv** [sjaehn/BSlizr#6]
The Makefile doesn't honor setting `CXXFLAGS` or `LDFLAGS` (but it really should!) and therefore setting `LDFLAGS` to achieve [full RELRO](https://tk-blog.blogspot.com/2009/02/relro-not-so-well-known-memory.html) is not possible out-of-the-box.

In case you need inspiration on how to do this, you can have a look at https://github.com/brummer10/GxPlugins.lv2/issues/23 and https://github.com/sadko4u/lsp-plugins/issues/4

**Comment by dvzrv** [comment]
For the record: I currently get around this by attaching Arch Linux' globally available `LDFLAGS` to the `$(CC)` lines.

**Comment by sjaehn** [comment]
I've to admit that I didn't put much effort on the makefile. Yet.
But I'll take a closer look on it when it gets a bit colder outside in DE (poor Berlin guys ;-)) in the next days.

**Comment by sjaehn** [comment]
CXXFLAGS and LDFLAGS added in c1b120094f9d3ae55244cec4b2b72013da04c06b . Linker flags -z relro -z set by default in d4040098b5a215bc5707ad2343fb8d0dd4be22da .
