### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by magnetophon** [sjaehn/BSlizr#7]
Hi,

Thanks for a great plugin!
I made a [NixOS package](https://github.com/NixOS/nixpkgs/pull/72256) for it.

I have some suggestions for the UI:

- Make the monitor switch respond to clicks as well as drags.
- Invert the release knob: low numbers on the left, high on the right.
- Add a reset button to the volume sliders, to quickly turn them all on again and make a new pattern.

**Comment by sjaehn** [comment]
Hi magnetophon,

thank you for the NixOS package and you suggestions.

Monitor switch. A switch in my TK is "only" a modified 0/1 slider. Thus it responds to dragging and to the position you click. This is different to the common behavior of a switch widget. I'll change it.

Attack & release knob. I know the labels "attack" and "release" are a bit misleading. I agree with you that low numbers on left and high on right for both knobs make sense as this is the most common behavior of knob widgets. But an inverted release knob makes also sense as the first knob describes an ascent and the second one a descent. I'll think about it.

Reset button. I thought about it. But I found too many arguments against it. (i) A reset button is a quick and easy way to throw away your plugin settings. Dangerous. (ii) There are other ways to reset a plugin state. Load default state, remove & add plugin ... (iii) If really needed, this should be a job for the host to provide it. And Ardour, Carla, ... provide reset buttons or menu items.

**Comment by magnetophon** [comment]
Thanks for considering my suggestions.
Maybe a way to counter (i) would be an undo button?

In the meantime I also made [packages for your other plugins](https://github.com/NixOS/nixpkgs/pull/72267)!

**Comment by sjaehn** [comment]
Monitor switch: Changed in 27acec27cfcd3b3e1a02a0bfd4dde25a12369275

**Comment by magnetophon** [comment]
Great, though I checked in BShapr and unfortunately the change didn't propagate there.
Isn't this something that should be changed in BWidgets?
I mean; every switch should toggle when clicked, not just the one in here.

**Comment by sjaehn** [comment]
BShapr and BSEQuencer still run on the old BWidgets. Updates will follow.

**Comment by magnetophon** [comment]
Ah, right.
Excuse my distrust!

**Comment by sjaehn** [comment]
B.Shapr and B.SEQuencer are updated, now. An undo button would be an interesting option for both of them. More important there than for B.Slizr. I think I will at it (there), but this will take some time.

**Comment by magnetophon** [comment]
Great, thanks!

**Comment by sjaehn** [comment]
Thanks, your package is now visible in repology. Therefore README.md updated in 595555a0aec99777435249a0f5d9531117792783

B.Shapr and B.SEQuencer received undo /redo functions in 1fd92913d5e746e0dae7e7be7b2c7c33fbe893cd and 83af5a785e5f50d2b0e160e8f8a5eb5bb01f42da , respectively.

**Comment by magnetophon** [comment]
Great, thanks!

So now that you have undo/redo, there's nothing against a pattern reset button, is there?

**Comment by sjaehn** [comment]
Also pattern reset buttons added to B.SEQuencer in https://github.com/sjaehn/BSEQuencer/commit/236bc014a8fb214772243fa0647e1a547a058334 and B.Shapr in https://github.com/sjaehn/BShapr/commit/9d431f08a531177e804a033054c4880fda7e26c1 , respectively.

B.Slizr, however, doesn't need reset, undo & redo within the plugin. You can quickly drag back the 16 (host controlled) sliders. And the host may provide reset, undo, and redo features (as Ardour does).

**Comment by magnetophon** [comment]
Cool, thanks!
